#!/bin/bash
#
# beautify.sh
#
# Usage: ./beautify.sh <file> ...
# will reformat all given files in the current directory
#
# ./beautify.sh -r <file> ...
# will reformat all given file (-patterns) in the current directory and travels
# recursively through all sub-directories and reformat those files.
#
#
# COPYRIGHT (C) 2012 AND ALL RIGHTS RESERVED BY
# MARC WEIDLER, ULRICHSTR. 12/1, 71672 MARBACH, GERMANY (MARC.WEIDLER@WEB.DE).
#
# ALL RIGHTS RESERVED. THIS SOFTWARE AND RELATED DOCUMENTATION ARE PROTECTED BY
# COPYRIGHT RESTRICTING ITS USE, COPYING, DISTRIBUTION, AND DECOMPILATION. NO PART
# OF THIS PRODUCT OR RELATED DOCUMENTATION MAY BE REPRODUCED IN ANY FORM BY ANY
# MEANS WITHOUT PRIOR WRITTEN AUTHORIZATION OF MARC WEIDLER OR HIS PARTNERS, IF ANY.
# UNLESS OTHERWISE ARRANGED, THIRD PARTIES MAY NOT HAVE ACCESS TO THIS PRODUCT OR
# RELATED DOCUMENTATION. SEE LICENSE FILE FOR DETAILS.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
# IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
# INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
# BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
# LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
# OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
# OF THE POSSIBILITY OF SUCH DAMAGE. THE ENTIRE RISK AS TO THE QUALITY AND
# PERFORMANCE OF THE PROGRAM IS WITH YOU. SHOULD THE PROGRAM PROVE DEFECTIVE,
# YOU ASSUME THE COST OF ALL NECESSARY SERVICING, REPAIR OR CORRECTION.
#
#set -x

astyle --version 2>/dev/null
if [[ $? == 0 ]]
then
  ASTYLE_VER=`(astyle --version >/dev/null) 2>&1 | sed 's/[[:alpha:]0[:space:]]//g'`
  ASTYLE_VER_MAJOR=`echo $ASTYLE_VER | awk -F. '{print $1}'`
  ASTYLE_VER_MINOR=`echo $ASTYLE_VER | awk -F. '{print $2}'`

  if [[ $ASTYLE_VER_MAJOR -ge 2 ]]
  then
    astyle --options=astyle.opt --verbose --formatted src/*.cpp src/*.h
  else
    echo "'astyle' version is too old - must be at least version 2."
  fi
else
  echo "'astyle' code beautifier not found. Please install and re-run again."
fi

